plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "maven-publish"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "org.yaml:snakeyaml:${project.snakeyaml_version}"
    include "org.yaml:snakeyaml:${project.snakeyaml_version}"

    testImplementation platform("org.junit:junit-bom:5.13.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    inputs.property "fabric_version", project.fabric_version
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand version: project.version,
                minecraft_version: project.minecraft_version,
                loader_version: project.loader_version,
                fabric_version: project.fabric_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release.set(25)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "LICENSE_${project.archives_base_name}" }
    }
    from("NOTICE")
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
